
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ReclamoException", targetNamespace = "http://services/")
public class ReclamoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ReclamoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ReclamoException_Exception(String message, ReclamoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ReclamoException_Exception(String message, ReclamoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.ReclamoException
     */
    public ReclamoException getFaultInfo() {
        return faultInfo;
    }

}
