
package com.market.svcentral;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Publicador", targetNamespace = "http://svcentral.market.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Publicador {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://svcentral.market.com/Publicador/saludarRequest", output = "http://svcentral.market.com/Publicador/saludarResponse")
    public String saludar();

}
